---

  - name: install libselinux-python package
    yum: name="libselinux-python" state="present"

  - name: disable SELinux in conf file
    selinux: state=disabled

  - name: install epel
    yum: name="epel-release" state="present"

  - name: upgrade all packages
    yum: name=* state=latest

  - name: remove unused packages
    yum: name={{ item }} state=absent
    with_items:
      - sendmail

  - name: stop unused services
    service: name={{ item }} enabled=no state=stopped
    ignore_errors: True
    with_items:
      - rpcbind

  - name: setup clock
    command: echo 'ZONE="{{ timezone }}"' > /etc/sysconfig/clock

  - name: setup timezone
    file: src="/usr/share/zoneinfo/{{ timezone }}" dest="/etc/localtime" state="link" force="yes"

  - name: ensure /home exists
    file: dest="/home" state="directory" owner="root" group="root" mode="0755"

  - name: "generate random password"
    command: "openssl rand -base64 16"
    register: ansible_password

  - name: create vcap group
    group: name="{{ upshot_user }}" gid="1000" state="present"

  - name: create vcap user
    user: name="{{ upshot_user }}" uid="1000" comment="vcap user" createhome="yes" home="{{ upshot_home }}" group="{{ upshot_user }}" password="{{ ansible_password.stdout }}"

  - name: enable sudo mdata for vcap
    template: src="sudoers.d/vcap.j2" dest="{{ pkg_prefix_path }}/etc/sudoers.d/{{ upshot_user }}" mode="0440"

  - name: overwrite vcap .bashrc
    template: src="bashrc.j2" dest="{{ upshot_home }}/.bashrc" owner="{{ upshot_user }}" group="{{ upshot_user }}"

  - name: create libdir
    file: path="{{ upshot_libdir }}" mode="0755" owner="root" group="{{ wheel_group_name }}" state="directory" recurse="yes"
    
  - name: upload upshot_include
    template: src="{{ item }}" dest="{{ upshot_libdir }}/{{ item }}" owner="root" group="root" mode="0755"
    with_items:
      - "common_include.sh"
      - "vcap_include.sh"
      - "reset_sshkey.sh"

  - name: upload upshot restart service
    template: src="{{ upshot_systemd_restart_service_src }}" dest="{{ upshot_systemd_restart_service_dest }}" mode="0755" owner="root"
      
  - name: start the upshot.service
    service: name="upshot.service" enabled="true" state="started"
    
  - name: setup local facts
    file: dest="/etc/ansible/facts.d" recurse="yes" state="directory"

  - name: install custom facts
    template: src="upshot_common.fact.j2" dest="/etc/ansible/facts.d/upshot_common.fact" mode="0755" owner="root"

  - name: reload local facts
    setup: filter="ansible_local"
