#!/bin/bash	
#
. /usr/lib/upshot/common_include.sh

MDATA_PORT=`mdata_get_wrapper vcap_port`
MDATA_VCAP_APPLICATION=`mdata_get_wrapper vcap_application`
MDATA_VCAP_SERVICES=`mdata_get_wrapper vcap_services`


PORT=${MDATA_PORT:-"3000"}
CF_INSTANCE_IP="`hostname --ip-address`"
CF_INSTANCE_GUID=`mdata_get_wrapper sdc:uuid`
CF_INSTANCE_ADDR=${CF_INSTANCE_IP}:${PORT}
CF_INSTANCE_INDEX=0
CF_INSTANCE_INTERNAL_IP="${CF_INSTANCE_IP}"
CF_INSTANCE_PORT="${PORT}"
CF_INSTANCE_PORTS="{}"
MEMORY_LIMIT="`free -m | grep Mem| awk '{print $2}'`m"
VCAP_APP_HOST="0.0.0.0"
VCAP_APP_PORT="${PORT}"
VCAP_APPLICATION=${MDATA_VCAP_APPLICATION:-{}}
VCAP_SERVICES=${MDATA_VCAP_SERVICES:-{}}

export MDATA_GET PORT CF_INSTANCE_IP CF_INSTANCE_ADDR CF_INSTANCE_GUID CF_INSTANCE_INDEX CF_INSTANCE_INTERNAL_IP CF_INSTANCE_PORT CF_INSTANCE_PORTS MEMORY_LIMIT VCAP_APP_HOST VCAP_APP_PORT VCAP_APPLICATION VCAP_SERVICES
